function classifier = trainFeatures(nomTrainFeatures, nomTrainLabels,k)
    % K-nearest algorithm time!!
    % {FITCKNN} = {FITClassifierK-NearestNeighbor}

    classifier = fitcknn(nomTrainFeatures, nomTrainLabels,  ... 
        Distance="euclidean",               ...
        NumNeighbors=k,                     ...
        DistanceWeight="squaredinverse",    ...
        Standardize=true,                   ... // Normalization
        Classnames=unique(nomTrainLabels)   ...
    );
    
